/** Hand-written OpenAPI 3.1 for the account API. Terminal and MCP consume the same paths. */

export const OPENAPI = {
  openapi: "3.1.0",
  info: { title: "Markov control plane", version: "0.1.0" },
  paths: {
    "/health": { get: { summary: "Liveness, venue cache sizes, program deploy bit" } },
    "/markets": { get: { summary: "Canonical markets with live venue rows" } },
    "/markets/{id}": { get: { summary: "Venue rows for one market" } },
    "/markets/{id}/depth": { get: { summary: "Live books" } },
    "/markets/{id}/candles": { get: { summary: "Pacifica kline only; Phoenix candles are not invented" } },
    "/markets/{id}/funding-history": { get: { summary: "One live funding print per venue" } },
    "/policy/check": { post: { summary: "Mandate checks, no side effects" } },
    "/routes/compare": { post: { summary: "Lifecycle cost ranking" } },
    "/routes/quote": { post: { summary: "Selected route only" } },
    "/trades/request": { post: { summary: "Receipt + owner signable" } },
    "/trades/reduce": { post: { summary: "Reduce-only Pacifica signable" } },
    "/positions/reduce": { post: { summary: "Alias of /trades/reduce" } },
    "/trades/submit": { post: { summary: "Relay signed Pacifica payload" } },
    "/orders/cancel": { post: { summary: "Owner-signed cancel_order" } },
    "/trades/{id}": { get: { summary: "Pending + receipt" } },
    "/receipts": { get: { summary: "Decision log; filter decision, kind, market" } },
    "/account": { get: { summary: "SIWS session + mandate summary" } },
    "/portfolio": { get: { summary: "Empty until a venue account returns balances" } },
    "/positions": { get: { summary: "Pacifica /positions" } },
    "/risk": { get: { summary: "Leverage is null when equity is unknown" } },
    "/mandate": { get: { summary: "Off-chain draft until program deploy" }, post: { summary: "Write a draft; owner SIWS" } },
    "/invest/propose": { post: { summary: "Pending invest rule; models never receive a signable" } },
    "/invest/rules": { get: { summary: "Owner rules" } },
    "/invest/rules/{id}": { get: { summary: "One rule + related receipts" } },
    "/approvals": { get: { summary: "Pending owner approvals" } },
    "/venues/capabilities": { get: { summary: "Adapter capabilities" } },
    "/auth/challenge": { post: { summary: "SIWS challenge" } },
    "/auth/verify": { post: { summary: "SIWS verify" } },
    "/auth/refresh": { post: { summary: "Rotate access token" } },
  },
};
